### ISSUE TITLE
ArrayIndexOutOfBoundsException when clicking ADD VIDEO with video field empty

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#8]
I started the app, opened a browser, created a room, waited a bit, then I clicked the ADD VIDEO button and an error appeared on the STDOUT/STDERR. This is the log:

```
Server is listening on 0.0.0.0:8080
Received: /world
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /status 5 0 https://www.youtube.com/watch?v=xy_NKN75Jhw
Received: /add false 
[ERROR] [03/07/2021 21:07:26.985] [default-akka.actor.default-dispatcher-2] [akka://defau
lt/user/$a] Index 2 out of bounds for length 2
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at vs.Room$$anon$1.addVideo(Room.scala:103)
        at vs.Room$$anon$1.handleReceivedMessage(Room.scala:136)
        at vs.Room$$anon$1$$anonfun$receive$1.applyOrElse(Room.scala:44)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at vs.Room$$anon$1.aroundReceive(Room.scala:27)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This doesn't have an effect on anything though.

This could be handled on the frontend by disabling the button when the field is empty, but the backend should cope with this in the first place.

**Comment by RobertLemmens** [comment]
yeah good find, top level we fail safely, but any inner system failure will throw errors on the backend in multiple places (there isnt allot of checking going on atm, should go through the code and make it more safe overal).

For now i've modified the backend to ignore requests if the result doesnt match exactly in count. Ive also added your suggestion;  disabled the button when empty and check for emptyness when sending again. You could still add garbage, a non existing video id for example, but that will just result in the frontend player to show an error.

Its in pr #9 on bug/indexoob branch now, will merge and deploy tommorow if testing works out fine.
